/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package chessGame;

public class App {

    public static void main(String[] args) {
        // SimpleGame game = new SimpleGame();
        ComplexGame game = new ComplexGame();
        game.setup();
        game.play(10);
    }
}
